[package]
name = "crdd-platform-access"
version = "0.0.0"
edition = "2024"
publish = false
rust-version = "1.94.1"

[dependencies]
windows-sys = { version = "=0.61.2", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Security_Authorization",
  "Win32_Security_Cryptography",
  "Win32_Storage_FileSystem",
  "Win32_System_Threading",
] }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
